# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .cluster_update_properties_py3 import ClusterUpdateProperties


class ManagementCluster(ClusterUpdateProperties):
    """The properties of a default cluster.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :param cluster_size: The cluster size
    :type cluster_size: int
    :param provisioning_state: The state of the cluster provisioning. Possible
     values include: 'Succeeded', 'Failed', 'Cancelled', 'Deleting', 'Updating'
    :type provisioning_state: str or
     ~vendored_sdks.models.ClusterProvisioningState
    :ivar cluster_id: The identity
    :vartype cluster_id: int
    :ivar hosts: The hosts
    :vartype hosts: list[str]
    """

    _validation = {
        'cluster_id': {'readonly': True},
        'hosts': {'readonly': True},
    }

    _attribute_map = {
        'cluster_size': {'key': 'clusterSize', 'type': 'int'},
        'provisioning_state': {'key': 'provisioningState', 'type': 'str'},
        'cluster_id': {'key': 'clusterId', 'type': 'int'},
        'hosts': {'key': 'hosts', 'type': '[str]'},
    }

    def __init__(self, *, cluster_size: int=None, provisioning_state=None, **kwargs) -> None:
        super(ManagementCluster, self).__init__(cluster_size=cluster_size, **kwargs)
        self.provisioning_state = provisioning_state
        self.cluster_id = None
        self.hosts = None
